add python opinion
db1group/db1-tech-radar pull request #20
Opened 2023-07-28 13:29 UTC by AlexandroHervis

2023-07-31 11:52 UTC, nilsonsrjunior requested changes
O termo correto no 2o parágrafo é engenheiro eletricista, e não elétrico. Avalie nas traduções se isso gera impacto também

2023-07-31 11:53 UTC, nilsonsrjunior requested changes
Sugestã ode ajuste:

De:
Tivemos um caso de uso em que um engenheiro elétrico especialista em manutenção de equipamentos conseguia escrever uma inteligencia artificial para planejar a melhor rotina de manutenção

Para:
Tivemos um caso de uso em que um engenheiro eletricista especialista em manutenção de equipamentos conseguia escrever uma inteligência artificial para planejar a melhor rotina de manutenção de ativos elétricos.

2023-07-31 11:54 UTC, nilsonsrjunior requested changes
Identifiquei alguns erros ortográficos e de acentuação, por favor fazer uma correção automática no texto

2023-07-31 11:56 UTC, nilsonsrjunior requested changes
Sugestão de alteração:

DE:
Projetos, Web, IoT, IA, Data Science, Machine Learning, DevOps, são alguns dos contextos que Python pode ser utilizada com sucesso.

Para:
Projetos web, IoT, IA, data science, machine learning e DevOps, são alguns dos contextos onde o uso de Python é perfeitamente aplicável.

2023-07-31 11:56 UTC, nilsonsrjunior requested changes
Faltou a referência do projeto de benchmark.

2023-09-01 12:46 UTC, nilsonsrjunior approved these changes

2023-09-01 12:47 UTC, erickantslima approved these changes

2023-09-01 12:47 UTC, merged